# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1111():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1111(self):
    self.driver.get("https://www.google.pl/")
    self.driver.set_window_size(945, 1012)
    self.driver.find_element(By.CSS_SELECTOR, "#L2AGLb > .QS5gu").click()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("bilety do kina")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "q").send_keys(Keys.DOWN)
    time.sleep(3)
    self.driver.find_element(By.NAME, "q").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "q").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "q").send_keys(Keys.DOWN)
    time.sleep(3)
    # self.driver.find_element(By.NAME, "q").send_keys("bilety do kina cena")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    time.sleep(10)
    self.driver.close()
  
