# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestPrzypadektestowyzmakowcem():
    def setup_method(self, method):
        self.driver = webdriver.Edge()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_przypadektestowyzmakowcem(self):
        tekst = "Coś"

        self.driver.get("https://www.google.pl/")
        self.driver.set_window_size(1337, 589)
        self.driver.find_element(By.XPATH, '//*[@id="L2AGLb"]/div').click()
        time.sleep(5)
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("makowiec")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        element = self.driver.find_element(By.CSS_SELECTOR, ".hlcw0c:nth-child(1) .LC20lb")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".hlcw0c:nth-child(1) .LC20lb").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".recommended-category:nth-child(3) > a").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".show-slide h3")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, ".show-slide img")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()

        # self.driver.close()
